---
- hosts: localhost
  tasks:
    - name: "add custom homebrew repos"
      community.general.homebrew_tap:
        name:
          [
            adoptopenjdk/openjdk,
            fishtown-analytics/dbt,
            homebrew/cask-versions,
            thoughtbot/formulae,
          ]

    - name: "Install homebrew packages"
      community.general.homebrew:
        name:
          [
            "coreutils",
            "direnv",
            "dnsmasq",
            "asdf",
            "fzf",
            "gnu-time",
            "gtop",
            "fd",
            "miller",
            "exa",
            "magic-wormhole",
            "ffsend",
            "up",
            "libtool",
            "libxslt",
            "libyaml",
            "readline",
            "tmux",
            "unzip",
            "vim",
            "watchman",
            "xz",
            "zlib",
            "tig",
            "adr-tools",
            "telnet",
          ]
        state: present
        update_homebrew: yes

    - name: "Modern Unix tools"
      shell: brew install curlie httpie procs cheat dog mcfly ripgrep fd broot duf dust delta exa bat
