---
- name: change to zsh
  hosts: all
  tasks:
    # 이건 비번 물어봐서 console에서 직접해야 하는군.
    #  - name: chsh
    #    command: "chsh -s /usr/bin/zsh sungyong"
     - name: Install oh my zsh
       shell: "curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh"
       ignore_errors: yes
     - name: Install Dir Color
       shell: "curl https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark --output ~/.dircolors"
       ignore_errors: yes
     - name: Add dir color to zshrc
       shell: "eval `dircolors ~/.dircolors` | tee -a ~/.zshrc"
     - name: Add p10k to zshrc
       shell: "eval `[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh` | tee -a ~/.zshrc"

